### ISSUE TITLE
Part-day public holiday

### ISSUE THREAD

**Issue by schinckel** [ryanss/holidays.py#20]
Hi there.

South Australia has a part day public holiday after 7pm on Christmas Eve and New Years Eve:

http://www.safework.sa.gov.au/show_page.jsp?id=2483#.VyR-0GNvN0c

(I'm guessing this is not something that will be supported any time soon: I've still not implemented it in my manual public-holiday stuff internally).

**Comment by ryanss** [comment]
If these days are only considered holidays after 7pm -- and therefore banks, government buildings, etc are open during the day -- I think these days should not be considered holidays considering the types of uses this library has.

Since the library makes it very easy to create custom holiday lists I think we should ignore these for now unless enough "part-day" holidays exist in other countries to warrant adding an optional `part_day` argument to the `Holiday` class.

**Comment by schinckel** [comment]
In Australia, it's not just "business hours" that are important: we have different pay rates for employees who work on public holidays.
